name: Build and Push Docker Image
'on':
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login -u "ifti1992" --password-Iftikhar@123
      - name: Build and push Docker image
        env:
          IMAGE_NAME: 'ifti1992/php-app:latest'
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
