name: Build and Push Docker Image
'on':
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: >
          echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login -u "${{
          secrets.DOCKERHUB_USERNAME }}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ifti1992
          DOCKERHUB_PASSWORD: Iftikhar@123
      - name: Build and push Docker image
        env:
          IMAGE_NAME: 'ifti1992/php-app:latest'
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
